version: "3"
services:
  chirpstack-gw-protobuf-translator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chirpstack-translator
    volumes:
      - ./:/chirpstack-gw-protobuf-translator
    restart: unless-stopped